### ISSUE TITLE
Z-targeting can target host body if possessing via Dissolution

### ISSUE THREAD

**Issue by Jackiecrazy** [coolAlias/DynamicSwordSkills#16]
What it says on the tin. Your view is locked straight up and you only hit yourself.

**Comment by Jackiecrazy** [comment]
Other than that, z-target also fails when there's something on your head or you're riding something. Predictably enough, you aim at your mount instead. Makes horseback fighting difficult, to say the least.

**Comment by coolAlias** [comment]
I'm not sure what you mean by the title or wearing something on your head, but if you are locking on to your mount you should still be able to swap targets.

That said, an exception to avoid locking on to your mount would definitely be a quality of life improvement.

**Comment by Jackiecrazy** [comment]
Dissolution gives a "possession" mechanic where you can possess undead after you die instead of respawning. From what little I have seen of the code it's mostly equivalent to mounting the mob in question. I can't remember what I meant about something being on my head either, I think it was doggy talents (there's an upgrade that allows you to put a wolf on your head, and you end up hitting your wolf when you start targeting)
Regardless, I totally forgot switching targets was a thing, sorry! Though, it would be a nice QoL to have the lock-on ignore anything that is riding you or that you ride.

**Comment by coolAlias** [comment]
Absolutely agreed - I don't know why I didn't think to exclude those from the targeting algorithm to begin with. Can't think of any situation where you'd want to target your mount or another entity riding you.
