### ISSUE TITLE
Update Checker is broken

### ISSUE THREAD

**Issue by nate2014jatc** [coolAlias/DynamicSwordSkills#17]
Version 6.0.1 (from curseforge) is saying that there's an update available, and pointing to your PMC page for the mod. 

However, it would appear that 6.0.1 is the latest release available from both sources.

![image](https://user-images.githubusercontent.com/11836893/56441967-1d7ae100-62ac-11e9-9c90-9606fb835cba.png)

**Comment by coolAlias** [comment]
I noticed that, too, but I'm not sure why.

I'll have to double-check the syntax in my [versionlist file.](https://github.com/coolAlias/DynamicSwordSkills/blob/master/src/main/resources/versionlist.json)

**Comment by nate2014jatc** [comment]
Thanks, I appreciate it.
