### ISSUE TITLE
Optional "Class" System in the DSS API [enhancment] [Suggestion]

### ISSUE THREAD

**Issue by FavouriteDragon** [coolAlias/DynamicSwordSkills#24]
Rather than writing my own class system, since I'm lazy, it'd be cool if there was already a class system in place in the API. Obviously it wouldn't be used by DSS, but it'd still be cool. Ex: Restrict skill menus and skills based on class

**Comment by coolAlias** [comment]
Sorry, this is out of scope, but check out issue #25 - these custom events should provide you what you need.
