### ISSUE TITLE
Server crash due to loot tables.

### ISSUE THREAD

**Issue by Akitori** [coolAlias/DynamicSwordSkills#4]
So my friend was walking around, generating chunks when the server up and died on them. Here's the crash report below.

[crash-2017-11-22_04.51.02-server.txt](https://github.com/coolAlias/DynamicSwordSkills/files/1496034/crash-2017-11-22_04.51.02-server.txt)

**Comment by coolAlias** [comment]
Thanks for the report! I'll get it fixed hopefully this weekend.
