### ISSUE TITLE
Prioritize mobs when targeting

### ISSUE THREAD

**Issue by coolAlias** [coolAlias/DynamicSwordSkills#8]
We wouldn't want to hurt those cute little bunnies when a horde of zombies is coming at us, now would we?

**Comment by mjac0by** [comment]
I'd like to be able to disable auto-targeting passive mobs without disabling auto-target entirely.

My modpack includes Project:Vibrant Journeys, which adds a couple tiny cosmetic critters, like snails and tiny passive spiders. So I'm often finding myself fighting zombies and when one dies suddenly focused on a snail. Hilarious but undesirable.
