### ISSUE TITLE
[1.12.2] Rising Cut doesn't trigger

### ISSUE THREAD

**Issue by Shahelion** [coolAlias/DynamicSwordSkills#9]
I don't know if the trigger combo got changed, but it doesn't work for me. While crouching, jump then attack. Nothing.

**Comment by coolAlias** [comment]
Thanks, I'll check it out.

**Comment by coolAlias** [comment]
I can't reproduce this - Rising Cut triggers perfectly fine for me in 1.12.

Are you perhaps using other mods?

**Comment by Shahelion** [comment]
I do have a number of mods, but I'm starting the pack over so if I encounter this again I'll re-open it.
